### PR TITLE
Sudoku_Solver

### PR DESCRIPTION
**Pull request by Raj-Gurjar**
By this Code, we can see if the Sudoku can be solved further or not.

### CODE REVIEW

**Comment by Raj-Gurjar** [comment]
> By this Code, we can see if the Sudoku can be solved further or not.

**Comment by aman18801** [comment]
What happened? Why did you closed it?

**Comment by Raj-Gurjar** [comment]
> What happened? Why did you closed it?

I think you have not accepted it due to some bug in it.

**Comment by Raj-Gurjar** [comment]
> > What happened? Why did you closed it?
> 
> I think you have not accepted it due to some bug in it.

But the code is totally fine.

**Pull request closed without merging**
